name: Deploy to Docker Registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: moby/setup-buildx-action@v1

      - name: Build Docker image
        run: docker buildx build -t short-url-image:${{ github.sha }} .

      - name: Push Docker image to registry
        run: docker push premmm123/short-url-image:${{ github.sha }}

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Log in to Docker registry
        run: docker login hub.docker.com -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull premmm123/short-url-image:${{ github.sha }}

      - name: Start Docker container
        run: docker run -d -p 80:3000 premmm123/short-url-image:${{ github.sha }}
